"""empty message

Revision ID: 1da1536699b0
Revises: d875049392b9
Create Date: 2019-05-02 18:41:34.240628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da1536699b0'
down_revision = 'd875049392b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_question_num'), 'question', ['num'], unique=False)
    op.drop_index('num', table_name='question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('num', 'question', ['num'], unique=True)
    op.drop_index(op.f('ix_question_num'), table_name='question')
    # ### end Alembic commands ###
