"""empty message

Revision ID: 8f14bc969cb8
Revises: 1da1536699b0
Create Date: 2019-05-25 16:51:55.480908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f14bc969cb8'
down_revision = '1da1536699b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('usernumber', sa.String(length=20, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('username', sa.String(length=50, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('password', sa.String(length=200, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('role', sa.SMALLINT(), nullable=False),
    sa.Column('dept', sa.String(length=50, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('openid', sa.String(length=100, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
