"""initial migration

Revision ID: 96ce7ff36f8d
Revises:
Create Date: 2019-04-25 14:37:31.291382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96ce7ff36f8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('openid', sa.String(length=50, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('gid', sa.INTEGER(), nullable=False),
    sa.Column('gname', sa.String(length=50, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('answers', sa.String(length=300, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('total', sa.INTEGER(), nullable=False),
    sa.Column('submit_time', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('isbn', sa.String(length=20, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('openid', sa.String(length=50, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('title', sa.String(length=100, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('image', sa.String(length=100, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('alt', sa.String(length=100, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('publisher', sa.String(length=100, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('summary', sa.String(length=1500, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('price', sa.String(length=100, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('rate', sa.Float(asdecimal=True), nullable=True),
    sa.Column('tags', sa.String(length=100, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('author', sa.String(length=100, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('count', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cSessionInfo',
    sa.Column('open_id', sa.String(length=100, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('uuid', sa.String(length=100, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('skey', sa.String(length=100, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('create_time', sa.DATETIME(), nullable=False),
    sa.Column('last_visit_time', sa.DATETIME(), nullable=False),
    sa.Column('session_key', sa.String(length=100, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('user_info', sa.String(length=2048, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.PrimaryKeyConstraint('open_id')
    )
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('openid', sa.String(length=100, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('bookid', sa.String(length=10, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('comment', sa.String(length=200, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('phone', sa.String(length=50, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('location', sa.String(length=50, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('gid', sa.INTEGER(), nullable=False),
    sa.Column('gname', sa.String(length=50, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('num', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.String(length=20, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('content', sa.String(length=200, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('answer', sa.String(length=30, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('score', sa.INTEGER(), nullable=False),
    sa.Column('result_a', sa.String(length=50, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('result_b', sa.String(length=50, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('result_c', sa.String(length=50, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('result_d', sa.String(length=50, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('num')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    op.drop_table('comments')
    op.drop_table('cSessionInfo')
    op.drop_table('books')
    op.drop_table('answers')
    # ### end Alembic commands ###
